set search_path to car_management;

CREATE TABLE RESERVE_TABLE(
    RESERVE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CAR_LICENSE_PLATE varchar(50) UNIQUE NOT NULL,
    USER_EMAIL VARCHAR(50) UNIQUE NOT NULL,
    PICK_DATE TIMESTAMP WITH TIME ZONE,
    DROP_DATE TIMESTAMP WITH TIME ZONE
);

CREATE TABLE T_CAR
(
    ID          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    BRAND        VARCHAR(50)    NOT NULL,
    MODEL        VARCHAR(50)    NOT NULL,
    ENGINE_TYPE  VARCHAR(10)    NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY  VARCHAR(20) NOT NULL DEFAULT 'system_user',
    LICENSE_PLATE varchar(50) NOT NULL UNIQUE DEFAULT 'AA-00-AA'
        REFERENCES RESERVE_TABLE(CAR_LICENSE_PLATE)
);

create table USER_DATA (
    user_id UUID PRIMARY KEY  DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL REFERENCES RESERVE_TABLE(USER_EMAIL),
    password VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user'
);


