set search_path to car_management;



CREATE TABLE T_CAR
(
    ID          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    BRAND        VARCHAR(50)    NOT NULL,
    MODEL        VARCHAR(50)    NOT NULL,
    ENGINE_TYPE  VARCHAR(10)    NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY  VARCHAR(20) NOT NULL DEFAULT 'system_user',
    LICENSE_PLATE varchar(50) NOT NULL UNIQUE DEFAULT 'AA-00-AA'
);

create table USER_DATA (
    user_id UUID PRIMARY KEY  DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
    phone VARCHAR(50) UNIQUE NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user'
);

CREATE TABLE RESERVE_TABLE(
    RESERVE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CAR_LICENSE_PLATE varchar(50) NOT NULL references T_CAR(LICENSE_PLATE),
    USER_PHONE VARCHAR(50) NOT NULL references USER_DATA(phone),
    PICK_DATE TIMESTAMP WITH TIME ZONE,
    DROP_DATE TIMESTAMP WITH TIME ZONE
);
